platform :ios, '8.0'
use_frameworks!

target 'DKCircularSlider_Example' do
  pod 'DKCircularSlider', :path => '../'

  target 'DKCircularSlider_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
